# Generated by Django 4.2.3 on 2023-07-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
